name: KiCad Jobset Run

on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kicad_pro'
      - '**.kicad_jobset'
  workflow_dispatch:

jobs:
  run-kicad-jobset:
    runs-on: ubuntu-latest
    container: kicad/kicad:9.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run KiCad Jobset
        run: |
          kicad-cli jobset run --file jlcpcb.kicad_jobset  buck-converter.kicad_pro

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KiCad-outputs
          path: output
